// fractal.wgsl.js — runtime shader assembled from the proven base estimator set.
//
// The base module is the shader as it existed before shape-specific estimator
// replacements. Keeping it intact lets new parameterised shapes replace only
// their estimator blocks without copying or risking unrelated mathematics.
// MATERIAL_WGSL imports this final string too, so the visible raymarch and the
// clearance probe always use identical maths.
import { FRACTAL_WGSL as BASE_FRACTAL_WGSL } from './fractal-base.wgsl.js';

const PENROSE_START = '// Penrose tiling engraved into a disc';
const GYROID_START = '// ---- Gyroid ---------------------------------------------------------------';
const GYROID_END = '// ---- Kleinian limit set ---------------------------------------------------';

const penroseStart = BASE_FRACTAL_WGSL.indexOf(PENROSE_START);
const gyroidStart = BASE_FRACTAL_WGSL.indexOf(GYROID_START, penroseStart);
if (penroseStart < 0 || gyroidStart < 0) {
  throw new Error('Retired Penrose estimator markers not found in base shader');
}

// ID 8 used to be the retired Penrose relief. It was deliberately kept out of
// the selector so ids after it never had to move. The slot is now reused for a
// genuinely three-dimensional canonical Apollonian sphere packing. The public
// UI calls it "Canonical Apollonian (Descartes)"; the internal id remains the
// old `penrose` key solely to preserve every already-shipped numeric id.
const APOLLONIAN_DESCARTES_WGSL = /* wgsl */ `// Canonical 3D Apollonian sphere packing (Descartes / Soddy-Gossett)
//
// Begin with one enclosing unit sphere (signed curvature -1) and four mutually
// tangent spheres inside it. Three inner spheres share the user-controlled
// curvature k; the fourth curvature k4 is NOT another free knob. It is the lower
// positive root of the 3D Descartes relation
//
//   (sum k_i)^2 = 3 sum(k_i^2)
//
// for (-1, k, k, k, k4). At the default
//
//   k = 1 + sqrt(6)/2 = 2.224744871...
//
// all four inner spheres are equal and their centres form a tetrahedron.
//
// The recursive packing is generated by the four DUAL Apollonian inversions.
// For each seed sphere i, its dual inversion sphere is orthogonal to the outer
// sphere and to the other three inner spheres. Inverting in it fixes those four
// spheres and swaps sphere i with the other Soddy-Gossett solution tangent to
// them. Repeating those involutions is exactly the gap-filling Apollonian group
// action, rather than a generic fold made to resemble a packing.
//
// Slot 0: common curvature k of seed spheres 1..3.
// Slot 1: finite group-word / recursion depth.
const APD_K_MIN : f32 = 2.22474487;
const APD_K_MAX : f32 = 3.2;
const APD_MAX_DEPTH : i32 = 24;

// Solve dot(x,a)=dot(x,b)=dot(x,c)=1. Cramer's rule in cross-product form.
// These three planes are the orthogonality conditions for one dual inversion
// sphere once the outer unit sphere has been eliminated.
fn apdSolveUnitPlanes(a : vec3<f32>, b : vec3<f32>, c : vec3<f32>) -> vec3<f32> {
  let bc = cross(b, c);
  let ca = cross(c, a);
  let ab = cross(a, b);
  let det = dot(a, bc);
  // The measured user interval never approaches a singular seed, but keep a
  // last-line denominator guard because shapeParams is a public uniform block.
  let safeDet = select(det, select(-1e-6, 1e-6, det >= 0.0), abs(det) < 1e-6);
  return (bc + ca + ab) / safeDet;
}

fn dePenrose(pos : vec3<f32>) -> DEResult {
  var res : DEResult;

  // The enclosing sphere fixes scale and framing. It is a boundary of the
  // construction, not a fifth solid ball to draw.
  let outer = length(pos) - 1.0;
  if (outer > 0.25) {
    res.dist = outer;
    res.trap = 0.25;
    return res;
  }

  // Three equal seed curvatures are user-owned. The fourth is derived from the
  // Soddy-Gossett quadratic; the lower root is the branch that meets the
  // symmetric tetrahedral seed at APD_K_MIN.
  let k = clamp(shapeParam(0u), APD_K_MIN, APD_K_MAX);
  let disc = max(9.0 * k * k - 18.0 * k - 3.0, 0.0);
  let k4 = 0.5 * (3.0 * k - 1.0 - sqrt(disc));
  let r = 1.0 / k;
  let r4 = 1.0 / max(k4, 1e-6);
  let h = 1.0 - r;
  let h4 = 1.0 - r4;

  // Build the four inner centres directly from the six tangency distances.
  // Each |c_i| = 1-r_i (internal tangency to the unit sphere), while
  // |c_i-c_j| = r_i+r_j (external tangency between inner spheres).
  let pair = 2.0 * r;
  let c1 = vec3<f32>(h, 0.0, 0.0);
  let x2 = (2.0 * h * h - pair * pair) / max(2.0 * h, 1e-6);
  let y2 = sqrt(max(h * h - x2 * x2, 1e-10));
  let c2 = vec3<f32>(x2, y2, 0.0);

  let pairDot = 0.5 * (2.0 * h * h - pair * pair);
  let x3 = pairDot / max(h, 1e-6);
  let y3 = (pairDot - x3 * x2) / max(y2, 1e-6);
  let z3 = sqrt(max(h * h - x3 * x3 - y3 * y3, 1e-10));
  let c3 = vec3<f32>(x3, y3, z3);

  let pair4 = r + r4;
  let dot4 = 0.5 * (h4 * h4 + h * h - pair4 * pair4);
  let x4 = dot4 / max(h, 1e-6);
  let y4 = (dot4 - x4 * x2) / max(y2, 1e-6);
  let z4 = (dot4 - x4 * x3 - y4 * y3) / max(z3, 1e-6);
  let c4 = vec3<f32>(x4, y4, z4);

  // Because each inner sphere is tangent internally to the unit sphere, its
  // centre direction n_i satisfies c_i = (1-r_i)n_i. A dual inversion sphere
  // orthogonal to the unit sphere and to three seed spheres has centre d with
  // d.n_j = 1 for those three j. That turns the four generators into four small
  // 3x3 solves and gives their radii from R^2 = |d|^2 - 1.
  let n1 = c1 / max(h, 1e-6);
  let n2 = c2 / max(h, 1e-6);
  let n3 = c3 / max(h, 1e-6);
  let n4 = c4 / max(h4, 1e-6);

  let g1 = apdSolveUnitPlanes(n2, n3, n4);
  let g2 = apdSolveUnitPlanes(n1, n3, n4);
  let g3 = apdSolveUnitPlanes(n1, n2, n4);
  let g4 = apdSolveUnitPlanes(n1, n2, n3);
  var gc = array<vec3<f32>, 4>(g1, g2, g3, g4);
  var gr2 = array<f32, 4>(
    max(dot(g1, g1) - 1.0, 1e-6),
    max(dot(g2, g2) - 1.0, 1e-6),
    max(dot(g3, g3) - 1.0, 1e-6),
    max(dot(g4, g4) - 1.0, 1e-6)
  );

  // Reduce the query point into the root Descartes cell. The interiors of the
  // dual spheres are precisely the recursive gaps. Inverting the deepest
  // violation at each step walks a group word back towards the four seed
  // spheres while `factor` accumulates the conformal scale change.
  let depth = i32(clamp(round(shapeParam(1u)), 4.0, f32(APD_MAX_DEPTH)));
  var p = pos;
  var factor = 1.0;
  var word = 0.0;
  for (var step = 0; step < APD_MAX_DEPTH; step = step + 1) {
    if (step >= depth) { break; }
    var which : i32 = -1;
    var best = 1.0;
    for (var j = 0; j < 4; j = j + 1) {
      let v = p - gc[j];
      let score = dot(v, v) / gr2[j];
      if (score < best) {
        best = score;
        which = j;
      }
    }
    if (which < 0) { break; }
    let v = p - gc[which];
    let q2 = max(dot(v, v), 1e-12);
    let inv = gr2[which] / q2;
    p = gc[which] + v * inv;
    factor = min(factor * inv, 1e18);
    word = word + 1.0;
  }

  // In the root cell the nearest member of the packing is one of the four seed
  // spheres. Pull that sphere distance back through the accumulated inversions.
  // A raw conformal pull-back slightly over-estimates away from the surface
  // because finite Euclidean distance is not infinitesimal. Against explicit
  // depth-8 packings (2900 spheres) over the full curvature interval, the worst
  // sampled ratio was about 1.06. 0.85 leaves a substantial conservative margin.
  var base = length(p - c1) - r;
  base = min(base, length(p - c2) - r);
  base = min(base, length(p - c3) - r);
  base = min(base, length(p - c4) - r4);
  let packing = 0.85 * base / max(factor, 1e-9);

  // Every generated sphere lies inside and tangent to the unit enclosing sphere,
  // so intersecting with that exact bound changes no packing geometry and gives
  // the camera a cheap safe step outside the construction.
  res.dist = max(packing, outer);
  res.trap = clamp(0.10 + 0.055 * word + 0.10 * (k - APD_K_MIN) / (APD_K_MAX - APD_K_MIN), 0.0, 1.0);
  return res;
}

`;

const withDescartes =
  BASE_FRACTAL_WGSL.slice(0, penroseStart)
  + APOLLONIAN_DESCARTES_WGSL
  + BASE_FRACTAL_WGSL.slice(gyroidStart);

const gStart = withDescartes.indexOf(GYROID_START);
const gEnd = withDescartes.indexOf(GYROID_END, gStart);
if (gStart < 0 || gEnd < 0) {
  throw new Error('Gyroid estimator markers not found after Descartes replacement');
}

const GYROID_WGSL = /* wgsl */ `// ---- Gyroid ---------------------------------------------------------------
//
// Schoen's gyroid, represented by the standard trigonometric nodal field
//
//   f(p) = cos x sin y + cos y sin z + cos z sin x.
//
// Slots 0..2 expose three genuine parameters of that construction:
//   0  cubic unit-cell size a
//   1  level-set offset t
//   2  wall half-thickness h
//
// Cell size is presented instead of frequency because it is the familiar
// geometric quantity. The shader derives k = 2*pi/a and uses that SAME k in the
// global Lipschitz bound sqrt(3)*k, so changing the cell size cannot leave the
// sphere-tracing safety divisor stale.
fn deGyroid(pos : vec3<f32>) -> DEResult {
  const R : f32 = 1.35;            // orbit-mode presentation clip only
  const SQRT3 : f32 = 1.73205081;  // exact bound on |grad f| before scaling

  // Last-line guards protect the estimator from a non-UI writer putting an
  // invalid value directly in the uniform block. The registry's user ranges
  // are much narrower than these guards.
  let cellSize = max(shapeParam(0u), 1e-4);
  let freq = 2.0 * PI / cellSize;
  let level = shapeParam(1u);
  let half = max(shapeParam(2u), 0.0);

  var res : DEResult;

  // The mathematical gyroid is infinite and triply periodic. Orbit mode clips
  // it to a ball so it can be viewed as an object; fly-through mode removes the
  // clip and exposes the periodic structure itself.
  let clipped = u.flyMode < 0.5;
  let ball = length(pos) - R;
  if (clipped && ball > 0.25) {
    res.dist = ball;
    res.trap = 0.4;
    return res;
  }

  let q = pos * freq;
  let s = sin(q);
  let c = cos(q);
  let f = c.x * s.y + c.y * s.z + c.z * s.x;

  // |grad f| <= sqrt(3) in field coordinates. q = p*freq multiplies
  // world-space derivatives by freq, so this remains a conservative distance
  // under-estimate at every Cell size without an empirical safety factor.
  let shell = (abs(f - level) - half) / (SQRT3 * freq);
  res.dist = select(shell, max(shell, ball), clipped);

  // The two faces look into the two interpenetrating labyrinths and keep their
  // existing separate palette bands.
  let face = select(0.0, 1.0, f - level >= 0.0);
  let aux = c.x * s.y - c.z * s.x;
  res.trap = 0.2 + 0.4 * face + 0.18 * clamp(0.5 + 0.35 * aux, 0.0, 1.0);
  return res;
}

`;

export const FRACTAL_WGSL =
  withDescartes.slice(0, gStart) + GYROID_WGSL + withDescartes.slice(gEnd);
